-- Wound assessment provenance and clinician-correction columns.
--
-- Additive only. Nothing is dropped or repurposed, so existing assessments keep
-- working and the change can be reverted by dropping these columns alone.
--
-- WHY EACH COLUMN EXISTS
--
-- ai_contour_cm / clinician_contour_cm
--   There was one contour column, so a clinician correcting the outline
--   overwrote the AI's version. That loses the audit trail the module needs, and
--   throws away the single most valuable asset the hospital can produce: paired
--   (AI attempt, expert correction) examples, which are exactly the training and
--   validation data a future model requires.
--
-- correction_reason
--   A clinician could approve an assessment but never say why they changed or
--   rejected it. The reason is what makes an override reviewable.
--
-- model_name / model_version / model_checksum / preprocessing_version
--   An assessment must remain attributable to the logic that produced it. Without
--   this, upgrading the analysis silently rewrites the meaning of every
--   historical result.
--
-- image_quality_score / image_quality_flags
--   Recorded so a measurement can be read against the quality of the photograph
--   it came from.
--
-- tissue_source
--   The important one. Granulation/slough/necrotic/epithelial percentages have
--   been generated by six fixed colour cutoffs with no validation and no dataset
--   to validate against. This column states where each row's percentages came
--   from, so the unvalidated ones can be identified rather than silently trusted.
--   Existing rows are backfilled to 'none', which is the truthful description of
--   what produced them.
--
-- epithelialised_pct / residual_raw_pct
--   Split-thickness graft donor sites, which are tracked as re-epithelialised
--   versus residual raw area rather than as a shrinking wound.

ALTER TABLE wound_assessments
  ADD COLUMN IF NOT EXISTS ai_contour_cm         JSONB,
  ADD COLUMN IF NOT EXISTS clinician_contour_cm  JSONB,
  ADD COLUMN IF NOT EXISTS correction_reason     TEXT,
  ADD COLUMN IF NOT EXISTS model_name            VARCHAR(80),
  ADD COLUMN IF NOT EXISTS model_version         VARCHAR(40),
  ADD COLUMN IF NOT EXISTS model_checksum        VARCHAR(80),
  ADD COLUMN IF NOT EXISTS preprocessing_version VARCHAR(40),
  ADD COLUMN IF NOT EXISTS image_quality_score   DECIMAL(4,3),
  ADD COLUMN IF NOT EXISTS image_quality_flags   JSONB DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS tissue_source         VARCHAR(20) DEFAULT 'none',
  ADD COLUMN IF NOT EXISTS epithelialised_pct    DECIMAL(5,2),
  ADD COLUMN IF NOT EXISTS residual_raw_pct      DECIMAL(5,2),
  ADD COLUMN IF NOT EXISTS no_wound_detected     BOOLEAN DEFAULT FALSE;

-- Every pre-existing row's tissue percentages came from the unvalidated colour
-- classifier. Say so, rather than leaving them indistinguishable from values a
-- clinician entered.
UPDATE wound_assessments
   SET tissue_source = 'none'
 WHERE tissue_source IS NULL;

-- Carry the existing contour forward as the AI's version. It was produced by the
-- automated pipeline, so that is where it belongs; clinician_contour_cm stays
-- NULL until someone actually corrects one.
UPDATE wound_assessments
   SET ai_contour_cm = contour_cm
 WHERE ai_contour_cm IS NULL
   AND contour_cm IS NOT NULL
   AND contour_cm::text <> '[]';

CREATE INDEX IF NOT EXISTS idx_wound_assessments_tissue_source
  ON wound_assessments(tissue_source);
