/**
 * Clinician Assistant — multi-modality diagnostic interpretation.
 *
 * Reads a patient's recorded investigations and vitals from Postgres, runs the
 * ported diagnostic engine over them, and presents the per-modality findings,
 * cross-modality correlations, impression and next steps.
 *
 * WHAT THIS MODULE DOES NOT DO. It does not re-implement burns, VTE risk,
 * pressure sore or nutritional assessment — this app already has those, and a
 * second copy would drift from the first. Where the engine's findings point at
 * one of them, the assistant links out to the existing module instead.
 *
 * The interpretation runs client-side and offline: the engine is pure, and a
 * ward round is exactly where the network is not.
 */

import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import {
  Activity, AlertTriangle, ArrowLeft, ClipboardList, ExternalLink, FileText,
  Loader2, RefreshCw, Save, Search, Stethoscope,
} from 'lucide-react';
import toast from 'react-hot-toast';
import { apiClient } from '../services/apiClient';
import {
  runForPatient, saveAnalysis, listForPatient, listRecent,
  ENGINE_VERSION, type RunResult, type SavedAnalysisSummary,
} from '../services/clinicianAssistant/clinicianAssistantService';
import type { Severity } from '../services/clinicianAssistant/engine/types';
import BedsideCalculators from '../components/clinicianAssistant/BedsideCalculators';
import ScanReportsPanel from '../components/clinicianAssistant/ScanReportsPanel';
import { buildFromPatientRecord } from '../services/clinicianAssistant/patientBridge';
import { runForContext } from '../services/clinicianAssistant/clinicianAssistantService';
import type { Extraction } from '../services/clinicianAssistant/engine/context';

/**
 * Findings that already have a dedicated module in this app. Matched on the
 * engine's finding ids so the assistant hands over rather than duplicating.
 */
const MODULE_HANDOFFS: { match: RegExp; label: string; href: string; why: string }[] = [
  { match: /vte|dvt|thrombo|d-?dimer/i, label: 'VTE / DVT Risk Assessment', href: '/patients', why: 'Score and prophylaxis are recorded in the existing risk assessment module.' },
  { match: /burn/i, label: 'Burn Care', href: '/burn-care', why: 'Parkland fluids and TBSA are handled by the burn module.' },
  { match: /pressure|braden/i, label: 'Pressure Sore Protocol', href: '/pressure-sore', why: 'Braden scoring and the prevention bundle live in the pressure sore module.' },
  { match: /nutrit|albumin|malnutrition/i, label: 'Nutrition & Meal Planning', href: '/patients', why: 'Requirements and meal plans are generated by the nutrition module.' },
  { match: /wound|ulcer/i, label: 'WoundProgress Monitor', href: '/wound-monitor', why: 'Serial wound measurement and healing analytics are tracked there.' },
  { match: /transfus|haemoglobin|anaemi/i, label: 'Blood Transfusion', href: '/blood-transfusion', why: 'Cross-match and transfusion records are kept in that module.' },
];

const SEVERITY_TONE: Record<string, string> = {
  critical: 'bg-red-100 text-red-800 border-red-300',
  'life-threatening': 'bg-red-100 text-red-800 border-red-300',
  severe: 'bg-red-50 text-red-700 border-red-200',
  moderate: 'bg-amber-100 text-amber-800 border-amber-300',
  mild: 'bg-yellow-50 text-yellow-800 border-yellow-200',
  normal: 'bg-green-100 text-green-800 border-green-300',
  none: 'bg-gray-100 text-gray-700 border-gray-200',
};

const tone = (s: Severity | string | undefined) =>
  SEVERITY_TONE[String(s || '').toLowerCase()] || 'bg-gray-100 text-gray-700 border-gray-200';

interface PatientRow {
  id: number | string;
  first_name?: string;
  last_name?: string;
  hospital_number?: string;
  ward?: string;
}

export default function ClinicianAssistantPage() {
  const [patients, setPatients] = useState<PatientRow[]>([]);
  const [search, setSearch] = useState('');
  const [selected, setSelected] = useState<PatientRow | null>(null);
  const [running, setRunning] = useState(false);
  const [saving, setSaving] = useState(false);
  const [result, setResult] = useState<RunResult | null>(null);
  const [history, setHistory] = useState<SavedAnalysisSummary[]>([]);
  const [recent, setRecent] = useState<SavedAnalysisSummary[]>([]);
  const [loading, setLoading] = useState(true);
  const [tab, setTab] = useState<'analysis' | 'calculators'>('analysis');
  // What the clinician chose to analyse from. 'choose' is the step the module
  // previously skipped — selecting a patient went straight to the record, so
  // the scan path had no way in.
  const [mode, setMode] = useState<'choose' | 'record' | 'scan'>('choose');
  // Record values kept so a scan can be merged with them rather than replacing.
  const [recordExtraction, setRecordExtraction] = useState<Extraction | null>(null);
  const [analysisSource, setAnalysisSource] = useState<'record' | 'scan' | 'mixed'>('record');

  useEffect(() => {
    (async () => {
      setLoading(true);
      try {
        const [p, r] = await Promise.all([
          apiClient.get('/patients').catch(() => null),
          listRecent(25).catch(() => []),
        ]);
        const rows: PatientRow[] = (p as any)?.patients || (Array.isArray(p) ? p : []);
        setPatients(rows);
        setRecent(r);
      } finally {
        setLoading(false);
      }
    })();
  }, []);

  const filtered = useMemo(() => {
    const q = search.trim().toLowerCase();
    if (!q) return patients.slice(0, 40);
    return patients
      .filter(p => `${p.first_name || ''} ${p.last_name || ''} ${p.hospital_number || ''}`.toLowerCase().includes(q))
      .slice(0, 40);
  }, [patients, search]);

  /** Choosing a patient opens the source chooser; it no longer auto-analyses. */
  const choosePatient = useCallback(async (patient: PatientRow) => {
    setSelected(patient);
    setResult(null);
    setRecordExtraction(null);
    setMode('choose');
    setHistory(await listForPatient(patient.id).catch(() => []));
  }, []);

  const run = useCallback(async (patient: PatientRow) => {
    setSelected(patient);
    setResult(null);
    setMode('record');
    setAnalysisSource('record');
    setRunning(true);
    try {
      const [r, h, bridge] = await Promise.all([
        runForPatient(patient.id),
        listForPatient(patient.id).catch(() => []),
        buildFromPatientRecord(patient.id).catch(() => null),
      ]);
      setResult(r);
      setHistory(h);
      setRecordExtraction(bridge?.extraction ?? null);
      if (r.sources.investigations === 0 && r.sources.vitals === 0) {
        toast('No recorded investigations or vitals for this patient', { icon: 'ℹ️' });
      }
    } catch (err: any) {
      toast.error(err?.message || 'Could not run the analysis');
    } finally {
      setRunning(false);
    }
  }, []);

  const save = async () => {
    if (!result || !selected) return;
    setSaving(true);
    try {
      await saveAnalysis(selected.id, result, { source: analysisSource });
      toast.success('Analysis saved to the patient record');
      setHistory(await listForPatient(selected.id).catch(() => []));
    } catch (err: any) {
      toast.error(err?.message || 'Could not save');
    } finally {
      setSaving(false);
    }
  };

  // Which existing modules this analysis should hand over to.
  const handoffs = useMemo(() => {
    if (!result) return [];
    const text = [
      ...result.analysis.impression,
      ...result.analysis.modules.flatMap(m => (m.findings || []).map((f: any) => `${f.id || ''} ${f.title || ''}`)),
    ].join(' ');
    return MODULE_HANDOFFS.filter(h => h.match.test(text));
  }, [result]);

  // ── Patient picker ─────────────────────────────────────────────────────
  if (!selected) {
    return (
      <div className="p-4 md:p-6 max-w-6xl mx-auto">
        <div className="mb-6">
          <h1 className="text-2xl font-bold text-gray-900 flex items-center gap-2">
            <Stethoscope className="w-6 h-6 text-primary-600" />
            Clinician Assistant
          </h1>
          <p className="text-sm text-gray-600 mt-1">
            Multi-modality interpretation of recorded investigations — haematology, biochemistry,
            blood gas, coagulation, cardiac markers, microbiology, urinalysis and ECG — with
            cross-modality correlation.
          </p>
        </div>

        <div className="bg-blue-50 border border-blue-200 rounded-lg p-3 mb-4 text-sm text-blue-900">
          Decision support only. Every finding is derived from values already in the record and must
          be checked against the source report before it informs treatment.
        </div>

        <div className="relative mb-4">
          <Search className="w-4 h-4 absolute left-3 top-3 text-gray-400" />
          <input
            value={search}
            onChange={e => setSearch(e.target.value)}
            placeholder="Search patient by name or hospital number"
            className="w-full pl-9 pr-3 py-2 border rounded-lg text-sm"
          />
        </div>

        {loading ? (
          <div className="flex justify-center py-16"><Loader2 className="w-8 h-8 animate-spin text-primary-600" /></div>
        ) : (
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
            <div className="lg:col-span-2 space-y-2">
              {filtered.map(p => (
                <button
                  key={String(p.id)}
                  onClick={() => choosePatient(p)}
                  className="w-full text-left bg-white border rounded-lg p-3 hover:border-primary-400 hover:shadow-sm transition flex items-center justify-between"
                >
                  <div>
                    <div className="font-medium text-gray-900">{p.first_name} {p.last_name}</div>
                    <div className="text-xs text-gray-500">{p.hospital_number}{p.ward ? ` · ${p.ward}` : ''}</div>
                  </div>
                  <Activity className="w-4 h-4 text-gray-400" />
                </button>
              ))}
              {filtered.length === 0 && <p className="text-sm text-gray-500 py-8 text-center">No matching patients.</p>}
            </div>

            <div>
              <h2 className="text-sm font-semibold text-gray-900 mb-2">Recent analyses</h2>
              <div className="space-y-2">
                {recent.length === 0 && <p className="text-xs text-gray-500">None yet.</p>}
                {recent.map(a => (
                  <div key={a.id} className="bg-white border rounded-lg p-2.5">
                    <div className="flex items-center justify-between gap-2">
                      <span className="text-sm text-gray-900 truncate">
                        {a.first_name || ''} {a.last_name || ''}
                      </span>
                      <span className={`px-1.5 py-0.5 rounded text-xs border ${tone(a.overall_severity)}`}>
                        {a.overall_severity}
                      </span>
                    </div>
                    <p className="text-xs text-gray-500 mt-0.5">
                      {new Date(a.analysed_at).toLocaleString()}
                    </p>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}
      </div>
    );
  }

  // ── Analysis view ──────────────────────────────────────────────────────
  return (
    <div className="p-4 md:p-6 max-w-5xl mx-auto">
      <button
        onClick={() => { setSelected(null); setResult(null); }}
        className="mb-4 text-sm text-gray-600 flex items-center gap-1 hover:text-gray-900"
      >
        <ArrowLeft className="w-4 h-4" /> Back to patients
      </button>

      <div className="bg-white border rounded-lg p-4 mb-4 flex flex-wrap items-start justify-between gap-3">
        <div>
          <h1 className="text-xl font-bold text-gray-900">{selected.first_name} {selected.last_name}</h1>
          <p className="text-sm text-gray-600">{selected.hospital_number}</p>
          {result && (
            <p className="text-xs text-gray-500 mt-1">
              {result.sources.investigations} investigation value(s), {result.sources.vitals} vitals set ·
              engine v{ENGINE_VERSION}
            </p>
          )}
        </div>
        {mode !== 'choose' && (
          <div className="flex gap-2">
            <button onClick={() => setMode('choose')} className="px-3 py-2 border rounded-lg text-sm">
              Change source
            </button>
            {mode === 'record' && (
              <button onClick={() => run(selected)} disabled={running} className="px-3 py-2 border rounded-lg text-sm flex items-center gap-2 disabled:opacity-50">
                <RefreshCw className={`w-4 h-4 ${running ? 'animate-spin' : ''}`} /> Re-run
              </button>
            )}
            <button onClick={save} disabled={!result || saving} className="px-3 py-2 bg-primary-600 text-white rounded-lg text-sm flex items-center gap-2 disabled:opacity-50">
              {saving ? <Loader2 className="w-4 h-4 animate-spin" /> : <Save className="w-4 h-4" />} Save to record
            </button>
          </div>
        )}
      </div>

      {/* The source chooser. Selecting a patient used to run the record
          analysis immediately, which left no way to reach the scan path at all. */}
      {mode === 'choose' && (
        <div className="space-y-3">
          <p className="text-sm text-gray-600">What should this analysis be based on?</p>

          <button
            onClick={() => run(selected)}
            className="w-full text-left bg-white border rounded-lg p-4 hover:border-primary-400 hover:shadow-sm transition flex items-start gap-3"
          >
            <ClipboardList className="w-5 h-5 text-primary-600 flex-shrink-0 mt-0.5" />
            <div>
              <div className="font-medium text-gray-900">Analyse existing records</div>
              <p className="text-sm text-gray-600">
                Uses the investigation results and vital signs already recorded for this patient.
                Nothing to scan; works offline from cached data.
              </p>
            </div>
          </button>

          <button
            onClick={() => { setMode('scan'); setAnalysisSource('scan'); }}
            className="w-full text-left bg-white border rounded-lg p-4 hover:border-primary-400 hover:shadow-sm transition flex items-start gap-3"
          >
            <FileText className="w-5 h-5 text-primary-600 flex-shrink-0 mt-0.5" />
            <div>
              <div className="font-medium text-gray-900">Scan reports (multiple pages)</div>
              <p className="text-sm text-gray-600">
                Photograph or upload printed reports — blood count, biochemistry, blood gas,
                culture, ECG. Values are read off each page, shown for checking, and interpreted
                together so findings can be correlated across modalities. Can be combined with
                what is already on record.
              </p>
            </div>
          </button>

          {history.length > 0 && (
            <p className="text-xs text-gray-500">
              {history.length} previous analysis(es) on file for this patient.
            </p>
          )}
        </div>
      )}

      {mode === 'scan' && !result && selected && (
        <div className="bg-white border rounded-lg p-4">
          <ScanReportsPanel
            patient={{
              ...(recordExtraction ? {} : {}),
              name: `${selected.first_name || ''} ${selected.last_name || ''}`.trim(),
              hospitalNumber: selected.hospital_number || '',
            } as any}
            recordExtraction={recordExtraction}
            onCancel={() => setMode('choose')}
            onAnalyse={async (extraction, documents) => {
              setRunning(true);
              try {
                // Build the patient context from the record so age, sex and
                // known comorbidity still inform the interpretation even when
                // the values themselves came off paper.
                const bridge = await buildFromPatientRecord(selected.id).catch(() => null);
                const ctx = bridge?.patient ?? null;
                if (!ctx) throw new Error('Could not load patient context');

                const analysis = runForContext(ctx, extraction);
                setResult({ analysis, unmapped: [], sources: { investigations: extraction.analytes.length, vitals: 0 } });
                setAnalysisSource(recordExtraction && recordExtraction.analytes.length ? 'mixed' : 'scan');
                setTab('analysis');
              } catch (err: any) {
                toast.error(err?.message || 'Could not analyse the scanned reports');
              } finally {
                setRunning(false);
              }
            }}
          />
        </div>
      )}

      {mode !== 'choose' && (
      <div className="flex gap-1 border-b mb-4">
        {([['analysis', 'Analysis'], ['calculators', 'Calculators']] as const).map(([id, label]) => (
          <button
            key={id}
            onClick={() => setTab(id)}
            className={`px-4 py-2 text-sm border-b-2 ${
              tab === id ? 'border-primary-600 text-primary-700 font-medium' : 'border-transparent text-gray-600'
            }`}
          >
            {label}
          </button>
        ))}
      </div>
      )}

      {mode !== 'choose' && tab === 'calculators' && (
        <BedsideCalculators
          prefill={{
            weightKg: result?.analysis.patient.weightKg ?? null,
            heightCm: result?.analysis.patient.heightCm ?? null,
            ageYears: result?.analysis.patient.age ?? null,
            sex: result?.analysis.patient.sex,
          }}
        />
      )}

      {tab === 'analysis' && running && (
        <div className="flex justify-center py-16"><Loader2 className="w-8 h-8 animate-spin text-primary-600" /></div>
      )}

      {tab === 'analysis' && result && !running && (
        <div className="space-y-4">
          <div className={`rounded-lg border p-4 ${tone(result.analysis.overallSeverity)}`}>
            <div className="text-xs uppercase tracking-wide font-semibold mb-1">Overall</div>
            <div className="text-lg font-bold">{result.analysis.overallSeverity}</div>
            {result.analysis.impression.length > 0 && (
              <ul className="mt-2 space-y-1 text-sm">
                {result.analysis.impression.map((line, i) => <li key={i}>· {line}</li>)}
              </ul>
            )}
          </div>

          {/* Values the engine could not interpret — surfaced, never hidden. */}
          {result.unmapped.length > 0 && (
            <div className="bg-amber-50 border border-amber-300 rounded-lg p-3">
              <p className="text-sm font-medium text-amber-900 flex items-center gap-1.5">
                <AlertTriangle className="w-4 h-4" /> {result.unmapped.length} recorded result(s) not interpreted
              </p>
              <ul className="mt-1.5 text-xs text-amber-900 space-y-0.5">
                {result.unmapped.slice(0, 12).map((u, i) => (
                  <li key={i}>{u.testName}: {u.value} {u.unit} — {u.reason.replace(/-/g, ' ')}</li>
                ))}
              </ul>
            </div>
          )}

          {handoffs.length > 0 && (
            <div className="bg-white border rounded-lg p-4">
              <h2 className="font-semibold text-gray-900 mb-2 flex items-center gap-1.5">
                <ExternalLink className="w-4 h-4" /> Continue in the dedicated module
              </h2>
              <div className="space-y-2">
                {handoffs.map((h, i) => (
                  <Link key={i} to={h.href} className="block border rounded-lg p-2.5 hover:border-primary-400 transition">
                    <div className="text-sm font-medium text-primary-700">{h.label}</div>
                    <div className="text-xs text-gray-600">{h.why}</div>
                  </Link>
                ))}
              </div>
            </div>
          )}

          {result.analysis.modules.filter((m: any) => (m.findings || []).length > 0).map((m: any, i: number) => (
            <div key={i} className="bg-white border rounded-lg p-4">
              <div className="flex items-center justify-between mb-2">
                <h3 className="font-semibold text-gray-900">{m.title || m.id}</h3>
                <span className={`px-2 py-0.5 rounded text-xs border ${tone(m.severity)}`}>{m.severity}</span>
              </div>
              <ul className="space-y-2">
                {(m.findings || []).map((f: any, j: number) => (
                  <li key={j} className="text-sm">
                    <span className="font-medium text-gray-900">{f.title}</span>
                    {f.detail && <p className="text-gray-600 text-xs mt-0.5">{f.detail}</p>}
                  </li>
                ))}
              </ul>
            </div>
          ))}

          {result.analysis.correlations.length > 0 && (
            <div className="bg-white border rounded-lg p-4">
              <h2 className="font-semibold text-gray-900 mb-2">Cross-modality correlations</h2>
              <ul className="space-y-2">
                {result.analysis.correlations.map((c: any, i: number) => (
                  <li key={i} className="text-sm">
                    <span className="font-medium">{c.title}</span>
                    {c.detail && <p className="text-gray-600 text-xs mt-0.5">{c.detail}</p>}
                  </li>
                ))}
              </ul>
            </div>
          )}

          {result.analysis.nextSteps.length > 0 && (
            <div className="bg-white border rounded-lg p-4">
              <h2 className="font-semibold text-gray-900 mb-2 flex items-center gap-1.5">
                <ClipboardList className="w-4 h-4" /> Suggested next steps
              </h2>
              <ul className="list-disc pl-5 text-sm text-gray-700 space-y-1">
                {result.analysis.nextSteps.map((s, i) => <li key={i}>{s}</li>)}
              </ul>
            </div>
          )}

          {history.length > 0 && (
            <div className="bg-white border rounded-lg p-4">
              <h2 className="font-semibold text-gray-900 mb-2 flex items-center gap-1.5">
                <FileText className="w-4 h-4" /> Previous analyses
              </h2>
              <div className="divide-y">
                {history.map(h => (
                  <div key={h.id} className="py-2 flex items-center justify-between gap-2">
                    <span className="text-xs text-gray-600">{new Date(h.analysed_at).toLocaleString()}</span>
                    <span className={`px-1.5 py-0.5 rounded text-xs border ${tone(h.overall_severity)}`}>
                      {h.overall_severity}
                    </span>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
